services:
  gitlab_gateway:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: ./start.sh
    restart: unless-stopped
    container_name: gitlab_gateway
    expose:
      - "8050"
    ports:
      - "8050:8050"
    env_file:
      - .env

volumes:
  gitlab_gateway_data: