"""Initial migration

Revision ID: 5a42140c7ad7
Revises: 
Create Date: 2024-08-12 12:43:16.829019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a42140c7ad7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('tread', sa.Integer(), nullable=True),
    sa.Column('caht_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('merge_request_id', sa.Integer(), nullable=False),
    sa.Column('action_merge_request', sa.String(), nullable=True),
    sa.Column('status_merge_request', sa.String(), nullable=True),
    sa.Column('created_at_merge_request', sa.DateTime(), nullable=True),
    sa.Column('updated_at_merge_request', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now', 'utc'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now', 'utc'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
