"""added model pipeline

Revision ID: a058590aca8b
Revises: 107b864759a0
Create Date: 2024-08-23 15:32:53.628531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a058590aca8b'
down_revision: Union[str, None] = '107b864759a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages_pipelines',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('tread', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=False),
    sa.Column('action_pipeline', sa.String(), nullable=True),
    sa.Column('status_pipeline', sa.String(), nullable=True),
    sa.Column('created_at_pipeline', sa.DateTime(), nullable=True),
    sa.Column('updated_at_pipeline', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(datetime('now', 'utc'))"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("(datetime('now', 'utc'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('messages', sa.Column('chat_id', sa.Integer(), nullable=False))
    op.drop_column('messages', 'caht_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('caht_id', sa.INTEGER(), nullable=False))
    op.drop_column('messages', 'chat_id')
    op.drop_table('messages_pipelines')
    # ### end Alembic commands ###
